# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12pyCdxIiVZFDNyy4ks7h9xzZEHIblY10
"""

import math

print("Questão 01 - Média Aritmética")
n1 = float(input("Digite o primeiro valor: "))
n2 = float(input("Digite o segundo valor: "))
n3 = float(input("Digite o terceiro valor: "))

media = (n1 + n2 + n3) / 3
print(f"A média aritmética dos 3 valores é: {media}\n")


print("Questão 02 - Idade atual e idade em 2050")
dataN = int(input("Digite o ano que você nasceu: "))
idd = 2026 - dataN
iddF = 2050 - dataN
print(f"Sua idade atual é {idd} e em 2050 você terá {iddF}\n")


print("Questão 03 - Conversão de dólar para real")
cot = float(input("Digite a cotação do dólar: "))
dol = float(input("Digite o valor em dólares: "))
rs = dol * cot
print(f"O valor em reais é: R$ {rs}\n")


print("Questão 04 - Novo salário com aumento de 25%")
salario = float(input("Digite o salário atual: "))
salarioN = salario * 1.25
print(f"O novo salário é: R$ {salarioN}\n")


print("Questão 05 - Área do losango")
d_mai = float(input("Digite a diagonal maior: "))
d_men = float(input("Digite a diagonal menor: "))
area = (d_mai * d_men) / 2
print(f"A área do losango é: {area}\n")


print("Questão 06 - Celsius para Fahrenheit")
cel = float(input("Digite a temperatura em Celsius: "))
fah = (celsius * 1.8) + 32
print(f"A temperatura em Fahrenheit é: {fah}\n")


print("Questão 07 - Quantidade de salários mínimos")
sal_min = float(input("Digite o valor do salário mínimo: "))
sal_func = float(input("Digite o salário do funcionário: "))
qtd = sal_func / sal_min
print(f"O funcionário ganha {qtd} salários mínimos\n")


print("Questão 08 - Novo peso (engordar e emagrecer)")
peso = float(input("Digite o peso atual: "))
peso_eng = peso * 1.15
peso_emag = peso * 0.80
print(f"Se engordar 15%: {peso_eng}")
print(f"Se emagrecer 20%: {peso_emag}\n")


print("Questão 09 - Hipotenusa do triângulo")
cat1 = float(input("Digite o primeiro cateto: "))
cat2 = float(input("Digite o segundo cateto: "))
hip = math.sqrt(cat1**2 + cat2**2)
print(f"A hipotenusa é: {hip}\n")


print("Questão 10 - Cálculos da esfera")
raio = float(input("Digite o raio: "))
comp = 2 * math.pi * raio
area = math.pi * (raio ** 2)
vol = (4/3) * math.pi * (raio ** 3)
print(f"Comprimento: {comp}")
print(f"Área: {area}")
print(f"Volume: {vol}\n")


print("Questão 11 - Equação do 2º grau")
a = float(input("Digite o valor de a: "))
b = float(input("Digite o valor de b: "))
c = float(input("Digite o valor de c: "))

delta = b**2 - 4*a*c
x1 = (-b + math.sqrt(delta)) / (2*a)
x2 = (-b - math.sqrt(delta)) / (2*a)

print(f"As raízes são: x1 = {x1} e x2 = {x2}\n")


print("Questão 12 - Tabuada")
num = int(input("Digite um número: "))

for i in range(1, 11):
    print(f"{num} x {i} = {num * i}\n")